<?php

return [
    'min_strength_to_respond' => 2,

    'search_words' => [
        'bejelentkezes' => [['scope' => 'login', 'lang' => 'hu']],
        'belepes' => [['scope' => 'login', 'lang' => 'hu']],
        'bejelentkezni' => [['scope' => 'login', 'lang' => 'hu']],
        'jelszo' => [['scope' => 'login', 'lang' => 'hu']],
        'felhasznalonev' => [['scope' => 'login', 'lang' => 'hu']],
        'login' => [['scope' => 'login', 'lang' => 'hu'], ['scope' => 'login', 'lang' => 'en']],
        'log in' => [['scope' => 'login', 'lang' => 'en']],
        'sign in' => [['scope' => 'login', 'lang' => 'en']],
        'username' => [['scope' => 'login', 'lang' => 'hu'], ['scope' => 'login', 'lang' => 'en']],
        'password' => [['scope' => 'login', 'lang' => 'en']],
        'credentials' => [['scope' => 'login', 'lang' => 'en']],

        'kijelentkezes' => [['scope' => 'logout', 'lang' => 'hu']],
        'kijelentkezni' => [['scope' => 'logout', 'lang' => 'hu']],
        'kilepes' => [['scope' => 'logout', 'lang' => 'hu']],
        'kilepni' => [['scope' => 'logout', 'lang' => 'hu']],
        'log out' => [['scope' => 'logout', 'lang' => 'hu'], ['scope' => 'logout', 'lang' => 'en']],
        'logout' => [['scope' => 'logout', 'lang' => 'hu'], ['scope' => 'logout', 'lang' => 'en']],
        'sign out' => [['scope' => 'logout', 'lang' => 'en']],
        'exit' => [['scope' => 'logout', 'lang' => 'en']],

        'kettenyezos' => [['scope' => 'two_factor_setup', 'lang' => 'hu']],
        'ketfaktoros' => [['scope' => 'two_factor_setup', 'lang' => 'hu'], ['scope' => 'recovery_codes', 'lang' => 'hu'], ['scope' => 'disable_2fa', 'lang' => 'hu']],
        '2fa' => [['scope' => 'two_factor_setup', 'lang' => 'hu'], ['scope' => 'two_factor_setup', 'lang' => 'en'], ['scope' => 'disable_2fa', 'lang' => 'hu'], ['scope' => 'disable_2fa', 'lang' => 'en']],
        'totp' => [['scope' => 'two_factor_setup', 'lang' => 'hu'], ['scope' => 'two_factor_setup', 'lang' => 'en']],
        'qr kod' => [['scope' => 'two_factor_setup', 'lang' => 'hu']],
        'hitelesites' => [['scope' => 'two_factor_setup', 'lang' => 'hu']],
        'beallitas' => [['scope' => 'two_factor_setup', 'lang' => 'hu']],
        'beallitasa' => [['scope' => 'two_factor_setup', 'lang' => 'hu']],
        'bekapcsolas' => [['scope' => 'two_factor_setup', 'lang' => 'hu']],
        'google' => [['scope' => 'two_factor_setup', 'lang' => 'hu'], ['scope' => 'two_factor_setup', 'lang' => 'en']],
        'authenticator' => [['scope' => 'two_factor_setup', 'lang' => 'hu'], ['scope' => 'two_factor_setup', 'lang' => 'en']],
        'two-factor' => [['scope' => 'two_factor_setup', 'lang' => 'en']],
        'twofactor' => [['scope' => 'two_factor_setup', 'lang' => 'en']],
        'two factor' => [['scope' => 'two_factor_setup', 'lang' => 'en']],
        'qr code' => [['scope' => 'two_factor_setup', 'lang' => 'en']],
        'enable two factor' => [['scope' => 'two_factor_setup', 'lang' => 'en']],
        'google authenticator' => [['scope' => 'two_factor_setup', 'lang' => 'en']],
        'authenticator app' => [['scope' => 'two_factor_setup', 'lang' => 'en']],

        'helyreallito' => [['scope' => 'recovery_codes', 'lang' => 'hu']],
        'hejreallito' => [['scope' => 'recovery_codes', 'lang' => 'hu']],
        'kod' => [['scope' => 'recovery_codes', 'lang' => 'hu']],
        'kodok' => [['scope' => 'recovery_codes', 'lang' => 'hu']],
        'recovery' => [['scope' => 'recovery_codes', 'lang' => 'hu'], ['scope' => 'recovery_codes', 'lang' => 'en']],
        'uj' => [['scope' => 'recovery_codes', 'lang' => 'hu']],
        'regeneral' => [['scope' => 'recovery_codes', 'lang' => 'hu']],
        'recovery code' => [['scope' => 'recovery_codes', 'lang' => 'en']],
        'recovery codes' => [['scope' => 'recovery_codes', 'lang' => 'en']],
        'regenerate recovery' => [['scope' => 'recovery_codes', 'lang' => 'en']],
        'regenerate codes' => [['scope' => 'recovery_codes', 'lang' => 'en']],

        'kikapcsolas' => [['scope' => 'disable_2fa', 'lang' => 'hu']],
        'letiltas' => [['scope' => 'disable_2fa', 'lang' => 'hu']],
        'multifactor' => [['scope' => 'disable_2fa', 'lang' => 'hu'], ['scope' => 'disable_2fa', 'lang' => 'en']],
        'kikapcsol' => [['scope' => 'disable_2fa', 'lang' => 'hu']],
        'disable two factor' => [['scope' => 'disable_2fa', 'lang' => 'en']],
        'turn off 2fa' => [['scope' => 'disable_2fa', 'lang' => 'en']],
        'disable 2fa' => [['scope' => 'disable_2fa', 'lang' => 'en']],
        'remove two factor' => [['scope' => 'disable_2fa', 'lang' => 'en']],
        'disable multifactor' => [['scope' => 'disable_2fa', 'lang' => 'en']],

        'regisztracio' => [['scope' => 'registration', 'lang' => 'hu']],
        'regisztralni' => [['scope' => 'registration', 'lang' => 'hu']],
        'regisztralas' => [['scope' => 'registration', 'lang' => 'hu']],
        'feliratkozas' => [['scope' => 'registration', 'lang' => 'hu']],
        'meghivo' => [['scope' => 'registration', 'lang' => 'hu']],
        'meghivas' => [['scope' => 'registration', 'lang' => 'hu']],
        'registration' => [['scope' => 'registration', 'lang' => 'en']],
        'register' => [['scope' => 'registration', 'lang' => 'en']],
        'sign up' => [['scope' => 'registration', 'lang' => 'en']],
        'invitation' => [['scope' => 'registration', 'lang' => 'en']],
        'invite' => [['scope' => 'registration', 'lang' => 'en']],

        'ugyintezo' => [['scope' => 'call_agent', 'lang' => 'hu']],
        'agent' => [['scope' => 'call_agent', 'lang' => 'hu'], ['scope' => 'call_agent', 'lang' => 'en']],
        'ember' => [['scope' => 'call_agent', 'lang' => 'hu']],
        'segitseg' => [['scope' => 'call_agent', 'lang' => 'hu']],
        'ugyfelszolgalat' => [['scope' => 'call_agent', 'lang' => 'hu']],
        'support' => [['scope' => 'call_agent', 'lang' => 'hu'], ['scope' => 'call_agent', 'lang' => 'en']],
        'hivas' => [['scope' => 'call_agent', 'lang' => 'hu']],
        'kapcsolat' => [['scope' => 'call_agent', 'lang' => 'hu']],
        'human' => [['scope' => 'call_agent', 'lang' => 'en']],
        'call agent' => [['scope' => 'call_agent', 'lang' => 'en']],
        'talk to someone' => [['scope' => 'call_agent', 'lang' => 'en']],
        'representative' => [['scope' => 'call_agent', 'lang' => 'en']],

        'esemeny' => [['scope' => 'events', 'lang' => 'hu']],
        'esemenyek' => [['scope' => 'events', 'lang' => 'hu']],
        'event' => [['scope' => 'events', 'lang' => 'hu'], ['scope' => 'events', 'lang' => 'en']],
        'naptar' => [['scope' => 'events', 'lang' => 'hu']],
        'kalendar' => [['scope' => 'events', 'lang' => 'hu']],
        'letrehozas' => [['scope' => 'events', 'lang' => 'hu']],
        'torles' => [['scope' => 'events', 'lang' => 'hu']],
        'szerkesztes' => [['scope' => 'events', 'lang' => 'hu']],
        'create' => [['scope' => 'events', 'lang' => 'hu'], ['scope' => 'events', 'lang' => 'en']],
        'update' => [['scope' => 'events', 'lang' => 'hu'], ['scope' => 'events', 'lang' => 'en']],
        'delete' => [['scope' => 'events', 'lang' => 'hu'], ['scope' => 'events', 'lang' => 'en']],
        'events' => [['scope' => 'events', 'lang' => 'en']],
        'calendar' => [['scope' => 'events', 'lang' => 'en']],
        'create event' => [['scope' => 'events', 'lang' => 'en']],
        'update event' => [['scope' => 'events', 'lang' => 'en']],
        'delete event' => [['scope' => 'events', 'lang' => 'en']],
        'edit event' => [['scope' => 'events', 'lang' => 'en']],
    ],

    'answers' => [
        'login' => [
            'hu' => 'A belépéshez a felhasználónév (e-mail) és a jelszó megadása szükséges. Ha a kétfaktoros hitelesítés be van kapcsolva, a bejelentkezés után a hitelesítő kód megadása is szükséges.',
            'en' => 'To log in, enter your username (email) and password. If two-factor authentication is enabled, you will also need to enter the authentication code after signing in.',
        ],
        'logout' => [
            'hu' => 'Kijelentkezni a weboldal jobb felső sarkában lévő felhasználónévre kattintva, majd a legördülő menüből a „Kijelentkezés” lehetőség választásával lehet.',
            'en' => 'To log out, click your username in the top-right corner of the page, then select "Log out" from the dropdown menu.',
        ],
        'two_factor_setup' => [
            'hu' => 'A kétfaktoros hitelesítés bekapcsolásához szükség lesz a Google Authenticator (vagy hasonló) alkalmazásra: olvasd be a QR kódot a beállításokban, majd a hitelesítő kód megadása után kattints a zöld gombra.',
            'en' => 'To enable two-factor authentication you need the Google Authenticator (or similar) app: scan the QR code in the settings, then enter the verification code and press the green button.',
        ],
        'recovery_codes' => [
            'hu' => 'Új helyreállító kód kérése csak a jelszó megadásával lehetséges, a kétfaktoros hitelesítés beállításoknál (Multifactor / kétfaktoros beállítások).',
            'en' => 'To regenerate recovery codes you must enter your password in the two-factor / multifactor authentication settings.',
        ],
        'disable_2fa' => [
            'hu' => 'A kétfaktoros hitelesítés kikapcsolása csak a jelszó megadásával lehetséges, a kétfaktoros (Multifactor) beállítások oldalán.',
            'en' => 'To disable two-factor authentication you must enter your password on the two-factor (multifactor) settings page.',
        ],
        'registration' => [
            'hu' => 'Az oldalra nem lehet közvetlenül regisztrálni; csak egy admin tud meghívni. A meghívó e-mailben kapott linkkel lehet regisztrációt befejezni.',
            'en' => 'Registration is not open to everyone; only an administrator can send an invitation. You can complete registration using the link in the invitation email.',
        ],
        'call_agent' => [
            'hu' => 'Ügyintézőt a chat ablak bal felső sarkában lévő „Ügyintéző hívása” (vagy „Call agent”) gombra kattintva lehet kérni.',
            'en' => 'To speak to an agent, click the "Call agent" (or "Request agent") button in the top-left area of the chat box.',
        ],
        'events' => [
            'hu' => 'Az eseményekkel kapcsolatos beállítások és műveletek (létrehozás, szerkesztés, törlés) a kalendár ikonnal jelölt menüben érhetők el.',
            'en' => 'Event-related options (create, update, delete) are available in the menu with the calendar icon.',
        ],
    ],
];
