<?php

namespace App\Enums;

enum ApiDomainErrorCode: string
{
    case EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS';
    case INVITATION_TOKEN_INVALID = 'INVITATION_TOKEN_INVALID';
    case INVITATION_TOKEN_EXPIRED = 'INVITATION_TOKEN_EXPIRED';
    case INVITATION_USER_NOT_PENDING = 'INVITATION_USER_NOT_PENDING';
    case PENDING_USER_INITIAL_PASSWORD_MISSING = 'PENDING_USER_INITIAL_PASSWORD_MISSING';
    case PASSWORD_RESET_TOKEN_ACTIVE = 'PASSWORD_RESET_TOKEN_ACTIVE';
    case PASSWORD_RESET_TOKEN_INVALID = 'PASSWORD_RESET_TOKEN_INVALID';
    case PASSWORD_RESET_TOKEN_EXPIRED = 'PASSWORD_RESET_TOKEN_EXPIRED';
    case USER_NOT_FOUND = 'USER_NOT_FOUND';
    case EVENT_NOT_FOUND = 'EVENT_NOT_FOUND';
    case EVENT_ACCESS_DENIED = 'EVENT_ACCESS_DENIED';
    case CONVERSATION_ACCESS_DENIED = 'CONVERSATION_ACCESS_DENIED';
    case CONVERSATION_NOT_FOUND = 'CONVERSATION_NOT_FOUND';
    case AGENT_MONITOR_ACCESS_DENIED = 'AGENT_MONITOR_ACCESS_DENIED';
    case INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
}
